# Generated by Django 4.2.16 on 2025-04-07 14:13

from django.db import migrations
import uuid

def create_dummy_plant_types(apps, schema_editor):
    PlantType = apps.get_model('core', 'PlantType')
    
    dummy_plants = [
        {
            'id': uuid.UUID('550e8400-e29b-41d4-a716-446655440000'),
            'name': 'Tomato',
            'scientific_name': 'Solanum lycopersicum',
            'common_diseases': ['Early Blight', 'Late Blight', 'Bacterial Spot']
        },
        {
            'id': uuid.UUID('550e8400-e29b-41d4-a716-446655440001'),
            'name': 'Potato',
            'scientific_name': 'Solanum tuberosum',
            'common_diseases': ['Late Blight', 'Early Blight', 'Blackleg']
        },
        {
            'id': uuid.UUID('550e8400-e29b-41d4-a716-446655440002'),
            'name': 'Wheat',
            'scientific_name': 'Triticum aestivum',
            'common_diseases': ['Rust', 'Fusarium Head Blight', 'Powdery Mildew']
        },
        {
            'id': uuid.UUID('550e8400-e29b-41d4-a716-446655440003'),
            'name': 'Corn',
            'scientific_name': 'Zea mays',
            'common_diseases': ['Gray Leaf Spot', 'Northern Corn Leaf Blight', 'Common Rust']
        }
    ]
    
    for plant_data in dummy_plants:
        PlantType.objects.create(**plant_data)

def remove_dummy_plant_types(apps, schema_editor):
    PlantType = apps.get_model('core', 'PlantType')
    PlantType.objects.filter(
        id__in=[
            '550e8400-e29b-41d4-a716-446655440000',
            '550e8400-e29b-41d4-a716-446655440001',
            '550e8400-e29b-41d4-a716-446655440002',
            '550e8400-e29b-41d4-a716-446655440003'
        ]
    ).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_dummy_plant_types,
            remove_dummy_plant_types
        ),
    ]
