# Generated by Django 4.2.16 on 2025-04-07 14:22

from django.db import migrations
import uuid

def create_dummy_diseases(apps, schema_editor):
    DiseaseType = apps.get_model('core', 'DiseaseType')
    
    dummy_diseases = [
        {
            'id': uuid.UUID('550e8400-e29b-41d4-a716-446655440010'),
            'name': 'Early Blight',
            'description': 'A fungal disease that affects tomatoes and potatoes, causing dark spots on leaves and stems.',
            'treatment': 'Remove infected leaves, apply fungicides, and practice crop rotation.',
            'plant_types': ['550e8400-e29b-41d4-a716-446655440000', '550e8400-e29b-41d4-a716-446655440001'],
            'severity': 'medium'
        },
        {
            'id': uuid.UUID('550e8400-e29b-41d4-a716-446655440011'),
            'name': 'Late Blight',
            'description': 'A devastating disease that can destroy entire tomato and potato crops.',
            'treatment': 'Apply fungicides preventatively, remove infected plants, and ensure good air circulation.',
            'plant_types': ['550e8400-e29b-41d4-a716-446655440000', '550e8400-e29b-41d4-a716-446655440001'],
            'severity': 'high'
        },
        {
            'id': uuid.UUID('550e8400-e29b-41d4-a716-446655440012'),
            'name': 'Rust',
            'description': 'A fungal disease that creates orange or brown spots on wheat leaves.',
            'treatment': 'Use resistant varieties, apply fungicides, and practice crop rotation.',
            'plant_types': ['550e8400-e29b-41d4-a716-446655440002'],
            'severity': 'medium'
        },
        {
            'id': uuid.UUID('550e8400-e29b-41d4-a716-446655440013'),
            'name': 'Gray Leaf Spot',
            'description': 'A fungal disease that affects corn, causing gray lesions on leaves.',
            'treatment': 'Use resistant hybrids, apply fungicides, and practice crop rotation.',
            'plant_types': ['550e8400-e29b-41d4-a716-446655440003'],
            'severity': 'medium'
        }
    ]
    
    for disease_data in dummy_diseases:
        DiseaseType.objects.create(**disease_data)

def remove_dummy_diseases(apps, schema_editor):
    DiseaseType = apps.get_model('core', 'DiseaseType')
    DiseaseType.objects.filter(
        id__in=[
            '550e8400-e29b-41d4-a716-446655440010',
            '550e8400-e29b-41d4-a716-446655440011',
            '550e8400-e29b-41d4-a716-446655440012',
            '550e8400-e29b-41d4-a716-446655440013'
        ]
    ).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_add_dummy_plant_types'),
    ]

    operations = [
        migrations.RunPython(
            create_dummy_diseases,
            remove_dummy_diseases
        ),
    ]
