# Generated by Django 4.2.16 on 2025-04-07 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_dummy_diseases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='report',
            name='detection_result',
        ),
        migrations.AddField(
            model_name='report',
            name='disease_detection',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='drought_detection',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='pest_detection',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='plant_detection',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='plant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.planttype'),
        ),
    ]
