# Generated by Django 4.2.16 on 2025-04-07 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_report_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('treatment', models.TextField()),
                ('plant_types', models.JSONField(default=list)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
            ],
        ),
    ]
