# Generated by Django 4.2.16 on 2025-04-14 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_pesttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseasetype",
            name="tag",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
